backtest/urls.py
from django.urls import path,re_path,include
from .data_loader.operate_database import db_insert
from .views import load_data,configurate_parameters,execute_strategy,upload_files

urlpatterns = [
    path('db_insert/',db_insert),
    path('configurate_parameters/',configurate_parameters,name="configurate_parameters"),
    path('load_data/',load_data,name="load_data"),
    path('upload_files/',upload_files,name="upload_files"),
    path('execute_strategy/',execute_strategy,name="execute_strategy"),

]

backtest/models.py
from django.db import models


# Create your models here.
class BinanceSpotKlineDaily(models.Model):
    current_time = models.DateTimeField()
    symbol = models.CharField(max_length=255)
    open_time = models.CharField(max_length=255)
    open_time_date = models.DateTimeField()
    open = models.DecimalField(max_digits=50,decimal_places=8)
    high = models.DecimalField(max_digits=50,decimal_places=8)
    low = models.DecimalField(max_digits=50,decimal_places=8)
    close = models.DecimalField(max_digits=50,decimal_places=8)
    volume = models.DecimalField(max_digits=50,decimal_places=8)
    close_time = models.CharField(max_length=255)
    close_time_date = models.DateTimeField()
    amount = models.DecimalField(max_digits=50, decimal_places=8)
    number_of_trades = models.DecimalField(max_digits=50, decimal_places=8)
    buy_volume = models.DecimalField(max_digits=50, decimal_places=8)
    buy_amount = models.DecimalField(max_digits=50, decimal_places=8)

class BinanceSpotKline1m(models.Model):
    current_time = models.DateTimeField()
    symbol = models.CharField(max_length=255)
    open_time = models.CharField(max_length=255)
    open_time_date = models.DateTimeField()
    open = models.DecimalField(max_digits=50,decimal_places=8)
    high = models.DecimalField(max_digits=50,decimal_places=8)
    low = models.DecimalField(max_digits=50,decimal_places=8)
    close = models.DecimalField(max_digits=50,decimal_places=8)
    volume = models.DecimalField(max_digits=50,decimal_places=8)
    close_time = models.CharField(max_length=255)
    close_time_date = models.DateTimeField()
    amount = models.DecimalField(max_digits=50, decimal_places=8)
    number_of_trades = models.DecimalField(max_digits=50, decimal_places=8)
    buy_volume = models.DecimalField(max_digits=50, decimal_places=8)
    buy_amount = models.DecimalField(max_digits=50, decimal_places=8)

backtest/forms.py
from django import forms
from django_ace import AceWidget

class CodeForm(forms.Form):
    code = forms.CharField(widget=AceWidget(
        mode='python',  # try for example "python"
        theme='monokai',  # try for example "twilight"
        wordwrap=False,
        width="500px",
        height="5px",
        minlines=None,
        maxlines=None,
        showprintmargin=True,
        showinvisibles=False,
        usesofttabs=True,
        tabsize=None,
        fontsize=None,
        toolbar=True,
        readonly=False,
        showgutter=True,  # To hide/show line numbers
        behaviours=True,  # To disable auto-append of quote when quotes are entered
    ))

backtest/views.py
# coding=utf-8
import time
import warnings
warnings.filterwarnings('ignore')

import time
import asyncio
import json
from . import utils

from django.shortcuts import render, HttpResponse, redirect
from .data_loader.operate_database import *
from .trade_engine.trade.trade import *
from .evaluator.performance_overview import *
from .evaluator.evalution_quantStats import *
from django.core.files.storage import FileSystemStorage
import os
from django.conf import settings
import hashlib
import importlib.util
from .forms import CodeForm


from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

def configurate_parameters(req):

    return render(req, "backtest/configurationParameters.html")

def load_data(req):
    if req.method=="POST":
        exchange = req.POST.get('exchange')
        initial_cash = int(req.POST.get('initial_cash'))
        symbol = req.POST.get('symbol')
        symbol_num = int(req.POST.get('symbol_num'))
        start_date = req.POST.get('start_date')
        end_date =  req.POST.get('end_date')
        interval =  req.POST.get('interval')
        handing_fee = float(req.POST.get('handing_fee')) / 100
        slip_fee = float(req.POST.get('slip_fee')) / 100
        symbol_list = symbol.split(' ')

        # 通过session存取数据
        req.session['interval'] = interval
        req.session['start_date'] = start_date
        req.session['end_date'] = end_date
        req.session['symbol_list'] = symbol_list
        req.session['exchange'] = exchange
        req.session['initial_cash'] = initial_cash
        req.session['handing_fee'] = handing_fee
        req.session['slip_fee'] = slip_fee

        all_data_json, benchmark_json, date_range_json = load_and_process_data(symbol_list, start_date, end_date,
                                                                               interval)
        req.session['all_data_json'] = all_data_json
        req.session['benchmark_json'] = benchmark_json
        req.session['date_range_json'] = date_range_json
    return render(req, "backtest/upload_files.html")

def upload_files(req):
    context = {}
    filename = None
    file_url = None
    if req.method == 'POST':
        save_path = settings.MEDIA_ROOT
        fs = FileSystemStorage(location=save_path)
        file_full_path = None
        if 'myfile' in req.FILES:
            myfile = req.FILES['myfile']
            filename = myfile.name
            strategy_name = filename.split('.')[0]
            file_full_path = os.path.join(save_path, myfile.name) # 文件完整路径
            req.session['strategy_name'] = strategy_name
            req.session['strategy_path'] = file_full_path
            # 检查文件是否已存在
            if os.path.exists(file_full_path):
                # 读取现有文件内容并计算哈希值
                with open(file_full_path, 'rb') as existing_file:
                    existing_file_content = existing_file.read()
                    existing_file_hash = hashlib.md5(existing_file_content).hexdigest()

                # 读取上传文件内容并计算哈希值
                uploaded_file_content = myfile.read()
                uploaded_file_hash = hashlib.md5(uploaded_file_content).hexdigest()

                # 比较哈希值
                if existing_file_hash == uploaded_file_hash:   # 如果一致，则 不用覆盖
                    context['message'] = 'File already exists but with the same content. Not overwriting.'
                else: # 如果不一致，则重写进该文件
                    context['message'] = 'File already exists with different content. Overwriting...'
                    myfile.seek(0)  # 重置文件指针到文件开头
                    with open(file_full_path, 'wb') as f:
                        f.write(uploaded_file_content)
            else:
                # 保存新文件
                filename = fs.save(myfile.name, myfile)
                file_url = fs.url(filename)
                context['file_url'] = file_url

            with open(fs.path(filename), 'r', encoding='utf-8') as file:
                file_content = file.read()
                context['file_content'] = file_content
                context['filename'] = filename

                # file_url是提供给用户的文件下载链接
                file_url = req.build_absolute_uri(settings.MEDIA_URL + filename)
                context['file_url'] = file_url

                # 创建表单实例并设置初始值
                form = CodeForm(initial={'code': file_content})
                context['form'] = form

            return render(req, "backtest/upload_files.html", context)

        if 'backtest' in req.POST:
            # 获取编码器中的代码，并存入原来上传路径中，目的在于运行用户在前端页面修改代码
            form = CodeForm(req.POST)
            if form.is_valid():
                code = form.cleaned_data['code']
                with open(req.session.get('strategy_path',None), 'w', encoding='utf-8') as file:
                    for line in code.splitlines():
                        file.write(line+'\n')
                print(code)
            return redirect('execute_strategy')



def execute_strategy(req):
    symbol_list = req.session.get('symbol_list',None)
    exchange = req.session.get('exchange',None)
    balance = req.session.get('initial_cash',None)
    handing_fee = req.session.get('handing_fee',None)
    slip_fee = req.session.get('slip_fee',None)
    strategy_name = req.session.get('strategy_name', None)
    strategy_path = req.session.get('strategy_path', None)

    all_data_json = req.session.get('all_data_json', None)
    benchmark_json = req.session.get('benchmark_json', None)
    date_range_json = req.session.get('date_range_json', None)

    # json -> dataframe or list
    all_data = pd.read_json(all_data_json, orient='records')
    date_range = json.loads(date_range_json)
    benchmark = pd.read_json(benchmark_json, orient='records')
    # 修改时间格式
    date_range = [utils.timestamp_datetime(x) for x in date_range]
    all_data['close_time'] = all_data['close_time'].apply(lambda x: utils.datetime_timestamp(x))
    all_data['close_time_date'] = all_data['close_time_date'].apply(lambda x: utils.timestamp_datetime(x))
    benchmark['close_time'] = benchmark['close_time'].apply(lambda x: utils.datetime_timestamp(x))
    benchmark['close_time_date'] = benchmark['close_time_date'].apply(lambda x: utils.timestamp_datetime(x))
    benchmark_price = benchmark["close"]
    benchmark_price.index = date_range

    ae_log_path = str(BASE_DIR) + f'\\backtest/analyse_engine/log/{strategy_name}.log'
    te_log_path = str(BASE_DIR) + f'\\backtest/trade_engine/log/{strategy_name}.log'
    try:
        if strategy_path and os.path.exists(strategy_path):
            parent_dirs = os.path.dirname(strategy_path)
            print(parent_dirs)
            sys.path.insert(0,parent_dirs)
            module_name = strategy_name
            spec = importlib.util.spec_from_file_location(module_name, strategy_path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            ae = None
            strategy_class = getattr(module, strategy_name)
            if strategy_class.deal_message and strategy_class.execute_AE_TE:   # 判断是否包含方法deal_message 和 execute_AE_TE
                ae = strategy_class(ae_log_path, strategy_name, symbol_list)
            te = Trade(strategy_name, te_log_path)

            # 执行AE 和 TE
            symbol_balance,symbol_portfolio_value,symbol_positions,symbol_signals, log_te_message = ae.execute_AE_TE(ae=ae, te=te, strategy_name=strategy_name, symbol_list=symbol_list, balance=balance, all_data=all_data,
                                                                                                   exchange=exchange,date_range=date_range,handing_fee=handing_fee, slip_fee=slip_fee, cal_ae_flag=True)  # cal_ae_flag :表示是否需要计算ae中的deal_message
            # 需要显示的 te 日志信息
            log_te_message

            symbol_portfolio_value["ALL"] = pd.Series(np.zeros(len(date_range)))
            symbol_balance["ALL"] = pd.Series(np.zeros(len(date_range)))
            symbol_positions["ALL"] = pd.Series(np.zeros(len(date_range)))
            for symbol in symbol_list:
                # list -> Series
                symbol_balance[symbol] = pd.Series(symbol_balance[symbol])
                symbol_positions[symbol] = pd.Series(symbol_positions[symbol])
                symbol_signals[symbol] = pd.Series(symbol_signals[symbol])
                symbol_portfolio_value[symbol] = pd.Series(symbol_portfolio_value[symbol])

                # print(symbol_signals[symbol][symbol_signals[symbol]!=0])

                # 计算整体表现
                symbol_portfolio_value["ALL"] += symbol_portfolio_value[symbol]
                symbol_balance["ALL"] += symbol_balance[symbol]
                symbol_positions["ALL"] += symbol_positions[symbol]


            symbol_returns = {}
            symbol_cum_returns = {}
            symbol_list_tmp = symbol_list.copy()
            symbol_list_tmp.append("ALL")
            for s in symbol_list_tmp:
                # 统一设置index为 Datetime
                try:
                    symbol_signals[s].index = date_range
                    # print(symbol_signals[symbol][symbol_signals[symbol] != 0])
                except KeyError as e:
                    print(f"KeyError {e}")
                except Exception:
                    raise
                symbol_balance[s].index = date_range
                symbol_positions[s].index = date_range
                symbol_portfolio_value[s].index = date_range

                # 计算symbol and ALL returns
                eval_quant = EvalByQuantStats(symbol_portfolio_value[s],benchmark_price)
                symbol_returns[s] = eval_quant.returns
                symbol_cum_returns[s] = eval_quant.cum_returns

            # 基准收益
            benchmark_returns = eval_quant.benchmark_returns
            benchmark_cum_returns = eval_quant.benchmark_cum_returns

            # 统一保存文件夹
            base_dir = str(BASE_DIR)
            output_dirs = str(BASE_DIR) + '\\' + f'templates/backtest/reports/PerformanceOverview/'

templates/backtest/configurationParameters.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>configurationParameters</title>
    <script src="{% static 'backtest/js/loading.js' %}"></script>
    <link rel="stylesheet" href="{% static 'backtest/css/loading.css' %}">
    <style>
      table{
        margin-left: auto;
        margin-right: auto;
      }
      td{
        padding: 10px;
        }
    </style>


</head>
<body>
    <div id="loading" style="display:none;">loading...</div>
    <div id="other">
        <h4>配置参数</h4>
        <form id="dataForm" action="{% url 'load_data' %}" method="post" target="_blank">
            {% csrf_token %}
            <table class="form-table">
              <tr>
                <td><label for="exchange">交易所:</label></td>
                <td><input type="text" id="exchange" name="exchange" value="binance" placeholder="binance"></td>
              </tr>
              <tr>
                <td><label for="initial_cash">初始资金:</label></td>
                <td><input type="text" id="initial_cash" name="initial_cash" value="1000000" placeholder="1000000"></td>
              </tr>
              <tr>
                <td><label for="symbol">币种:</label></td>
                <td><input type="text" id="symbol" name="symbol" value="EOSETH ACEUSDT" placeholder="EOSETH ACEUSDT"></td>
                <td><label for="symbol_num">币种个数:</label></td>
                <td><input type="text" id="symbol_num" name="symbol_num" value="2" placeholder="2"></td>
              </tr>
              <tr>
                <td colspan="2">
                  <label for="start_date">开始时间:</label>
                  <input type="text" id="start_date" name="start_date" value="2024-2-10" placeholder="%Y-%m-%d">
                  <label for="end_date">结束时间:</label>
                  <input type="text" id="end_date" name="end_date" value="2024-10-12" placeholder="%Y-%m-%d">
                    <label for="interval">周期:</label>
                  <input type="text" id="interval" name="interval" value="daily" placeholder="daily">
                </td>
              </tr>
              <tr>
        <!--        <td>-->
        <!--          <label for="take_fee">吃单:</label>-->
        <!--          <input type="text" id="take_fee" name="take_fee" value="0.03" placeholder="0.03">-->
        <!--        </td>-->
        <!--        <td>-->
        <!--          <label for="make_fee">挂单:</label>-->
        <!--          <input type="text" id="make_fee" name="make_fee" value="0.03" placeholder="0.03">-->
        <!--        </td>-->
                <td>
                  <label for="slip_fee">滑点:</label>
                  <input type="text" id="slip_fee" name="slip_fee" value="0.05" placeholder="0.05">
                </td>
                <td>
                  <label for="handing_fee">手续费:</label>
                  <input type="text" id="handing_fee" name="handing_fee" value="0.05" placeholder="0.05">
                </td>
              </tr>
              <tr>
                <td colspan="2" style="text-align: center;">
                  <input type="submit" value="提交">
                </td>
              </tr>
            </table>
        </form>
    </div>
</body>
</html>

templates/backtest/performance_overview.html
{% extends "backtest/performance_overview/base.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Performance overview</title>
    <link rel="stylesheet" href="{% static 'backtest/css/styles.css' %}">
    <script src="{% static 'backtest/js/scripts.js' %}"></script>
</head>
<body>

{% block content %}
<div class="layout">
    <div class="tabs">
        <button class="tablinks" onclick="openTab(event, 'Performance')">绩效概览</button>
        <button class="tablinks" onclick="openTab(event, 'Holdings')">持仓分析</button>
<!--        <button class="tablinks" onclick="openTab(event, 'DailyDetails')">每日明细</button>-->
        <button class="tablinks" onclick="openTab(event, 'Signals')">信号分析</button>
        <button class="tablinks" onclick="openTab(event, 'Returns')">收益分析</button>
    </div>
    <div class="select-container">
        <div id="Performance" class="tabcontent">
            <h3>绩效概览</h3>
            {% with performance_path=performance_combined.performance_path performance_indcators=performance_combined.performance_indcators show_report_path=performance_combined.show_report_path %}
                {% include "backtest/performance_overview/performance.html" %}
            {% endwith %}
        </div>

        <div id="Holdings" class="tabcontent" style="display:none">
            <h3>持仓分析</h3>
            {% include performance_position_path %}
        </div>

<!--        <div id="DailyDetails" class="tabcontent" style="display:none">-->
<!--            <h3>每日明细</h3>-->
<!--            <p>这里是每日明细的内容。</p>-->
<!--        </div>-->

        <div id="Signals" class="tabcontent" style="display:none">
            <h3>信号分析</h3>
            <div id="signal-container">
                {% for symbol, signal_path in symbol_signal_path.items %}
                    <button class="signal-btn" data-path="{{ signal_path }}">{{ symbol }}</button>
                    <div id="{{ symbol }}" class="signal_path_hidden">
                        {% with signal_path=signal_path %}
                            {% include signal_path %}
                        {% endwith %}
                    </div>
                {% endfor %}
            </div>
        </div>

        <div id="Returns" class="tabcontent" style="display:none">
            <h3>收益分析</h3>
            <div id="return-container">
                {% for symbol_re, returnValues in symbol_returns_combined.items %}
                    {% with return_path=returnValues.0 symbol_indicators=returnValues.1 %}
                        <button class="return-btn" data-path="{{ return_path }}">{{ symbol_re }}</button>
                        <div id="{{ symbol_re }}" class="return_path_hidden">
                            {% include "backtest/performance_overview/returns.html" %}
                        </div>
                    {% endwith %}
                {% endfor %}
            </div>
        </div>

    </div>
</div>
{% endblock %}
</body>
</html>

templates/backtest/upload_files.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Upload Strategy File</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.min.js"></script>
    <script src="{% static 'backtest/js/loading.js' %}"></script>
    <link rel="stylesheet" href="{% static 'backtest/css/loading.css' %}">
    <style>
        .backtest {
            position: fixed;
            top: 5px;
            right: 5px;
            width: 300px;
            height: auto;
            background: white;
            padding: 10px;
            box-shadow: -2px 2px 5px rgba(0,0,0,0.2);
            z-index: 1000;
        }
        #id_code{
            width: 90%;
            height: 100vh;
            border: 1px solid #ccc;
            background-color: black; /* 设置背景颜色为黑色 */
            color: white; /* 设置文本颜色为白色 */
        }

    </style>
    <script>
        var uploadDiv = document.querySelector('.upload');
        var uploadButton = document.getElementById('uploadButton');

        if (uploadButton) {
            uploadButton.addEventListener('click', function(event) {
                event.preventDefault();
                uploadDiv.style.display = 'hidden';
            });
        }

    </script>
</head>
<body>
    <div id="loading" style="display:none;">loading...</div>
    <div id="other">
        <div class="upload">
            <h1>Upload Strategy File</h1>
            <form method="post" action="{% url 'upload_files' %}" enctype="multipart/form-data" target="_blank">
                {% csrf_token %}
                <input type="file" name="myfile" accept=".py">
                <button type="submit" id="uploadButton">Upload</button>
            </form>
        </div>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

        {% if file_content %}
            <div>
                <div class="code">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="backtest">
                            <button type="submit" name="backtest" value="backtest" id="backtestButton">开始回测</button>
                        </div>
                    </form>
                </div>
            </div>

    <!--            <div class="backtest">-->
    <!--                <form method="post">-->
    <!--                    {% csrf_token %}-->
    <!--                    <button type="submit" name="backtest" value="backtest" id="backtestButton">开始回测</button>-->
    <!--                </form>-->
    <!--            </div>-->
        {% endif %}
    </div>
</body>
</html>